version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Building Spring Boot app..."
      - mvn clean package -DskipTests

artifacts:
  files:
  
  base-directory: .
